name: Update GitHub Stats

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download stats
        run: |
          curl -o stats.svg "https://github-readme-stats.vercel.app/api?username=NicoMartina&show_icons=true&theme=radical"
          curl -o langs.svg "https://github-readme-stats.vercel.app/api/top-langs?username=NicoMartina&layout=compact&theme=radical"
          curl -o trophies.svg "https://github-profile-trophy.vercel.app/?username=NicoMartina&theme=algolia&no-bg=true&margin-w=15"

      - name: Commit files
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "GitHub Bot"
          git add .
          git commit -m "update stats" || exit 0
          git push
