name: Render GitHub Stats

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install deps
        run: sudo apt-get install -y librsvg2-bin

      - name: Download SVGs
        run: |
          curl -o stats.svg "https://github-readme-stats.vercel.app/api?username=NicoMartina&show_icons=true&theme=radical"
          curl -o langs.svg "https://github-readme-stats.vercel.app/api/top-langs?username=NicoMartina&layout=compact&theme=radical"
          curl -o streak.svg "https://streak-stats.demolab.com?user=NicoMartina&theme=radical"

      - name: Convert to PNG
        run: |
          rsvg-convert stats.svg -o stats.png
          rsvg-convert langs.svg -o langs.png
          rsvg-convert streak.svg -o streak.png

      - name: Commit
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "GitHub Bot"
          git add *.png
          git commit -m "update rendered stats" || exit 0
          git push
